name: track_fit_app
description: "TFG DAM2 Villaba, Bryan y Iker"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.2.1
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  palette_generator: ^0.3.3
  image_picker: ^1.0.0
  webview_flutter: ^4.0.7
  go_router: ^7.1.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/TrackFit_blanco_sin_fondo_sin_letra_limpio.png"

  adaptive_icon_foreground: "assets/logos/TrackFit_blanco_sin_fondo_sin_letra_limpio.png"
  adaptive_icon_background: "#161616"
  # si quieres usar imágenes distintas para cada plataforma:
  # image_path_android: "assets/icons/app_icon_android.png"
  # image_path_ios:     "assets/icons/app_icon_ios.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logos/
    - assets/images/
    - assets/icons/
    - .env
