name: track_fit_app
description: "TFG DAM2 Villaba, Bryan y Iker"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  shared_preferences: ^2.0.0
  palette_generator: ^0.3.3
  image_picker: ^1.0.0
  supabase_flutter: ^1.5.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
